<?php

/**
 * Configuración de formularios SRI
 * Mapeo de casilleros a códigos de cuenta y reglas de cálculo
 */

return [
    'f103' => [
        'name' => 'Formulario 103 - Retenciones en la Fuente del Impuesto a la Renta',
        'frequency' => 'monthly',
        'retention_codes' => [
            '303' => ['description' => 'Honorarios profesionales y dietas', 'percentage' => 10],
            '304' => ['description' => 'Servicios predomina mano de obra', 'percentage' => 2],
            '307' => ['description' => 'Servicios entre sociedades', 'percentage' => 2],
            '308' => ['description' => 'Servicios entre sociedades 1%', 'percentage' => 1],
            '309' => ['description' => 'Servicios publicidad y comunicacion', 'percentage' => 1],
            '310' => ['description' => 'Transporte privado de pasajeros', 'percentage' => 1],
            '312' => ['description' => 'Transferencia de bienes muebles', 'percentage' => 1],
            '319' => ['description' => 'Arrendamiento de bienes inmuebles', 'percentage' => 8],
            '320' => ['description' => 'Seguros y reaseguros', 'percentage' => 1],
            '322' => ['description' => 'Por pagos a no residentes', 'percentage' => 25],
            '323' => ['description' => 'Por rendimientos financieros', 'percentage' => 2],
            '332' => ['description' => 'Compras locales materia prima', 'percentage' => 1],
            '340' => ['description' => 'Otras retenciones aplicables 1%', 'percentage' => 1],
            '341' => ['description' => 'Otras retenciones aplicables 2%', 'percentage' => 2],
            '342' => ['description' => 'Otras retenciones aplicables 8%', 'percentage' => 8],
            '343' => ['description' => 'Otras retenciones aplicables 25%', 'percentage' => 25],
            '344' => ['description' => 'Aplicables a otros porcentajes', 'percentage' => 0],
            '345' => ['description' => 'Relacion de dependencia', 'percentage' => 0],
        ],
    ],

    'f104' => [
        'name' => 'Formulario 104 - Impuesto al Valor Agregado',
        'frequency' => 'monthly',
        'casilleros_ventas' => [
            '401' => 'Ventas locales gravadas tarifa diferente de 0% (excluye activos fijos)',
            '403' => 'Ventas de activos fijos gravadas tarifa diferente de 0%',
            '405' => 'Ventas locales gravadas tarifa 0% (que no dan derecho a CT)',
            '407' => 'Ventas locales gravadas tarifa 0% (que dan derecho a CT)',
            '409' => 'Exportaciones de bienes',
            '411' => 'Exportaciones de servicios',
            '413' => 'Total ventas y otras operaciones',
            '419' => 'Ventas netas (413 - transferencias no objeto o exentas)',
            '429' => 'Total impuesto generado',
        ],
        'casilleros_compras' => [
            '500' => 'Adquisiciones y pagos gravados tarifa diferente de 0% (con CT)',
            '501' => 'Adquisiciones locales de activos fijos gravadas tarifa diferente de 0% (con CT)',
            '502' => 'Adquisiciones y pagos no gravados',
            '507' => 'Adquisiciones y pagos gravados tarifa diferente de 0% (sin CT)',
            '510' => 'Importaciones de bienes (excluye activos fijos)',
            '511' => 'Importaciones de activos fijos',
            '518' => 'Total adquisiciones',
            '520' => 'Impuesto causado en adquisiciones',
        ],
        'casilleros_liquidacion' => [
            '601' => 'Impuesto causado (generado - adquisiciones)',
            '602' => 'Credito tributario del mes anterior',
            '605' => 'Retenciones que le han sido efectuadas',
            '609' => 'Total impuesto a pagar',
            '611' => 'Impuesto a pagar',
            '615' => 'Credito tributario para el proximo mes',
        ],
    ],

    'f101' => [
        'name' => 'Formulario 101 - Declaracion del Impuesto a la Renta Sociedades',
        'frequency' => 'annual',
        'sections' => [
            'activos' => [
                '311' => 'Total del activo',
                '312' => 'Total activos corrientes',
                '313' => 'Efectivo y equivalentes al efectivo',
                '314' => 'Activos financieros',
                '315' => 'Inventarios',
                '316' => 'Servicios y otros pagos anticipados',
                '317' => 'Activos por impuestos corrientes',
                '330' => 'Total activo no corriente',
                '331' => 'Propiedad, planta y equipo neto',
                '332' => 'Propiedades de inversion',
                '334' => 'Activos intangibles',
                '335' => 'Activos por impuestos diferidos',
            ],
            'pasivos' => [
                '411' => 'Total del pasivo',
                '412' => 'Total pasivo corriente',
                '413' => 'Cuentas y documentos por pagar',
                '414' => 'Obligaciones con instituciones financieras',
                '415' => 'Obligaciones con el IESS',
                '416' => 'Beneficios a empleados por pagar',
                '417' => 'Otras obligaciones corrientes',
                '430' => 'Total pasivo no corriente',
                '431' => 'Obligaciones con instituciones financieras LP',
                '432' => 'Pasivos por impuestos diferidos',
            ],
            'patrimonio' => [
                '501' => 'Total patrimonio neto',
                '502' => 'Capital',
                '503' => 'Aportes futuras capitalizaciones',
                '504' => 'Reservas',
                '505' => 'Otros resultados integrales',
                '506' => 'Resultados acumulados',
                '507' => 'Resultados del ejercicio',
            ],
            'ingresos' => [
                '601' => 'Total ingresos',
                '602' => 'Ingresos por actividades ordinarias',
                '603' => 'Otros ingresos',
            ],
            'costos_gastos' => [
                '701' => 'Total costos',
                '702' => 'Costo de ventas y produccion',
                '801' => 'Total gastos',
                '802' => 'Gastos de venta',
                '803' => 'Gastos administrativos',
                '804' => 'Gastos financieros',
                '805' => 'Otros gastos',
            ],
            'conciliacion_tributaria' => [
                '801' => 'Utilidad del ejercicio',
                '803' => '(-) Participacion trabajadores 15%',
                '804' => 'Gastos no deducibles',
                '806' => 'Utilidad gravable',
                '809' => 'Impuesto causado',
                '812' => '(-) Anticipo determinado',
                '814' => '(-) Retenciones que le han efectuado',
                '819' => 'Impuesto a la renta causado',
                '859' => 'Total impuesto a pagar',
            ],
        ],
    ],

    'f102' => [
        'name' => 'Formulario 102 - Declaracion del Impuesto a la Renta Personas Naturales',
        'frequency' => 'annual',
    ],

    'ats' => [
        'name' => 'Anexo Transaccional Simplificado',
        'frequency' => 'monthly',
        'tipos_comprobante' => [
            '01' => 'Factura',
            '02' => 'Nota o boleta de venta',
            '03' => 'Liquidacion de compra de bienes y prestacion de servicios',
            '04' => 'Nota de credito',
            '05' => 'Nota de debito',
            '06' => 'Guia de remision',
            '07' => 'Comprobante de retencion',
            '08' => 'Boletos espectaculos publicos',
            '09' => 'Tiquetes o vales emitidos por maquinas registradoras',
            '11' => 'Pasajes expedidos por empresas de aviacion',
            '12' => 'Documentos emitidos por instituciones financieras',
            '15' => 'Comprobante de venta emitido en el exterior',
            '18' => 'Documentos autorizados utilizados en ventas excepto N/C N/D',
            '19' => 'Comprobante de pago de cuotas o aportes',
            '20' => 'Documentos por servicios administrativos emitidos por instituciones del estado',
            '21' => 'Carta de porte aereo',
            '41' => 'Comprobante de venta emitido por reembolso',
            '42' => 'Documento retención presuntiva y retención emitida por propio vendedor exportador',
            '43' => 'Liquidacion para explotacion y exploracion de hidrocarburos',
            '44' => 'Comprobante de contribuciones y aportes',
            '45' => 'Liquidacion de compra de bienes muebles usados',
            '47' => 'Nota de credito por reembolso emitida por intermediario',
            '48' => 'Nota de debito por reembolso emitida por intermediario',
        ],
        'tipos_identificacion' => [
            '04' => 'RUC',
            '05' => 'Cedula',
            '06' => 'Pasaporte',
            '07' => 'Consumidor final',
            '08' => 'Identificacion del exterior',
        ],
        'codigos_sustento' => [
            '01' => 'Credito tributario para declaracion de IVA',
            '02' => 'Costo o Gasto para declaracion de IR (no genera CT IVA)',
            '03' => 'Activo Fijo - Credito Tributario para declaracion de IVA',
            '04' => 'Activo Fijo - Costo o Gasto para declaracion de IR (no genera CT IVA)',
            '05' => 'Liquidacion gastos de viaje, hospedaje y alimentacion',
            '06' => 'Inventario - Credito Tributario para declaracion de IVA',
            '07' => 'Inventario - Costo o Gasto para declaracion de IR (no genera CT IVA)',
            '08' => 'Valor pagado para solicitar reembolso de Gasto',
            '09' => 'Reembolso por Siniestros',
            '10' => 'Distribucion de Dividendos, Beneficios o Utilidades',
            '15' => 'Pagos por concepto de consumo propio',
        ],
    ],

    'rdep' => [
        'name' => 'RDEP - Relacion de Dependencia',
        'frequency' => 'annual',
    ],
];
