<?php

namespace Tests\Feature\Api;

use App\Enums\DocumentType;
use App\Models\SRI\SequentialNumber;
use App\Models\Tenant\Company;
use App\Models\Tenant\EmissionPoint;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;
use Tests\Traits\CreatesTestTenant;

class OnboardingApiTest extends TestCase
{
    use RefreshDatabase;
    use CreatesTestTenant;

    protected function setUp(): void
    {
        parent::setUp();
        $this->setUpTenantContext();
    }

    /**
     * THE MOST IMPORTANT TEST (SRI migration continuity).
     *
     * A migrating user whose last issued Factura was 000001234 passes
     * last_number = 1234. We must store current_number = 1234 so that the
     * NEXT sequential generated by EmissionPoint::getNextSequential() is 1235.
     */
    public function test_sequentials_preserve_sri_numbering_continuity(): void
    {
        $response = $this->postJson('/api/v1/onboarding/sequentials', [
            'emission_point_id' => $this->emissionPoint->id,
            'sequentials' => [
                ['document_type' => '01', 'last_number' => 1234],
                ['document_type' => '04', 'last_number' => 0],
            ],
        ]);

        $response->assertOk()
            ->assertJsonPath('success', true);

        $this->assertDatabaseHas('sequential_numbers', [
            'tenant_id' => $this->tenant->id,
            'emission_point_id' => $this->emissionPoint->id,
            'document_type' => '01',
            'current_number' => 1234,
        ]);

        // Response advertises the correct next number.
        $factura = collect($response->json('data.sequentials'))
            ->firstWhere('document_type', '01');
        $this->assertSame(1234, $factura['current_number']);
        $this->assertSame(1235, $factura['next_number']);

        // The actual generator must return last_number + 1.
        $emissionPoint = EmissionPoint::find($this->emissionPoint->id);
        $next = $emissionPoint->getNextSequential('01');
        $this->assertSame(1235, $next);

        // A fresh-start type (last_number = 0) must yield 1 next.
        $nextNc = $emissionPoint->getNextSequential('04');
        $this->assertSame(1, $nextNc);
    }

    public function test_sequentials_endpoint_upserts_existing_row(): void
    {
        SequentialNumber::create([
            'tenant_id' => $this->tenant->id,
            'emission_point_id' => $this->emissionPoint->id,
            'document_type' => DocumentType::FACTURA,
            'current_number' => 5,
        ]);

        $this->postJson('/api/v1/onboarding/sequentials', [
            'emission_point_id' => $this->emissionPoint->id,
            'sequentials' => [
                ['document_type' => '01', 'last_number' => 900],
            ],
        ])->assertOk();

        $this->assertSame(1, SequentialNumber::where('emission_point_id', $this->emissionPoint->id)
            ->where('document_type', '01')->count());

        $this->assertDatabaseHas('sequential_numbers', [
            'emission_point_id' => $this->emissionPoint->id,
            'document_type' => '01',
            'current_number' => 900,
        ]);
    }

    public function test_sequentials_rejects_negative_last_number(): void
    {
        $this->postJson('/api/v1/onboarding/sequentials', [
            'emission_point_id' => $this->emissionPoint->id,
            'sequentials' => [
                ['document_type' => '01', 'last_number' => -1],
            ],
        ])->assertStatus(422);
    }

    public function test_sequentials_rejects_emission_point_from_other_tenant(): void
    {
        $other = $this->createSecondTenant();
        $otherCompany = Company::factory()->create(['tenant_id' => $other['tenant']->id]);
        $otherBranch = \App\Models\Tenant\Branch::factory()->create([
            'tenant_id' => $other['tenant']->id,
            'company_id' => $otherCompany->id,
        ]);
        $otherEp = EmissionPoint::factory()->create([
            'tenant_id' => $other['tenant']->id,
            'branch_id' => $otherBranch->id,
        ]);

        $this->postJson('/api/v1/onboarding/sequentials', [
            'emission_point_id' => $otherEp->id,
            'sequentials' => [
                ['document_type' => '01', 'last_number' => 10],
            ],
        ])->assertStatus(422);
    }

    public function test_get_sequentials_returns_current_rows(): void
    {
        SequentialNumber::create([
            'tenant_id' => $this->tenant->id,
            'emission_point_id' => $this->emissionPoint->id,
            'document_type' => DocumentType::FACTURA,
            'current_number' => 42,
        ]);

        $response = $this->getJson('/api/v1/onboarding/sequentials?emission_point_id=' . $this->emissionPoint->id);

        $response->assertOk();
        $row = collect($response->json('data.sequentials'))->firstWhere('document_type', '01');
        $this->assertSame(42, $row['current_number']);
        $this->assertSame(43, $row['next_number']);
    }

    /**
     * Status transitions: with a company present has_company is true; after
     * complete, completed becomes true.
     */
    public function test_status_reflects_company_and_completion(): void
    {
        // The trait already created a company + branch + emission point.
        $response = $this->getJson('/api/v1/onboarding/status');
        $response->assertOk()
            ->assertJsonPath('data.has_company', true)
            ->assertJsonPath('data.has_certificate', true) // factory withSignature()
            ->assertJsonPath('data.has_establishment', true)
            ->assertJsonPath('data.completed', false);

        $this->postJson('/api/v1/onboarding/complete')->assertOk();

        $this->getJson('/api/v1/onboarding/status')
            ->assertOk()
            ->assertJsonPath('data.completed', true);

        $this->tenant->refresh();
        $this->assertTrue((bool) data_get($this->tenant->settings, 'onboarding_completed'));
    }

    public function test_status_without_company_is_all_false(): void
    {
        // Fresh tenant with no company.
        $second = $this->createSecondTenant();
        \Laravel\Sanctum\Sanctum::actingAs($second['user']);

        $this->getJson('/api/v1/onboarding/status')
            ->assertOk()
            ->assertJsonPath('data.has_company', false)
            ->assertJsonPath('data.has_certificate', false)
            ->assertJsonPath('data.has_establishment', false)
            ->assertJsonPath('data.has_sequentials', false)
            ->assertJsonPath('data.completed', false);
    }

    public function test_company_create_and_status_transition(): void
    {
        // Use a fresh tenant without a company.
        $second = $this->createSecondTenant();
        \Laravel\Sanctum\Sanctum::actingAs($second['user']);

        $payload = [
            'ruc' => '1790012345001',
            'business_name' => 'Empresa Demo S.A.',
            'address' => 'Av. Amazonas 123',
            'email' => 'demo@example.com',
            'taxpayer_type' => 'sociedad',
            'obligated_accounting' => true,
            'sri_environment' => '1',
        ];

        $this->postJson('/api/v1/onboarding/company', $payload)
            ->assertCreated()
            ->assertJsonPath('success', true)
            ->assertJsonPath('data.ruc', '1790012345001')
            // Frontend contract: sociedad round-trips back as sociedad.
            ->assertJsonPath('data.taxpayer_type', 'sociedad');

        $this->assertDatabaseHas('companies', [
            'tenant_id' => $second['tenant']->id,
            'ruc' => '1790012345001',
            // Persisted as the DB enum value.
            'taxpayer_type' => 'juridical',
        ]);

        $this->getJson('/api/v1/onboarding/status')
            ->assertOk()
            ->assertJsonPath('data.has_company', true);
    }

    public function test_company_update_does_not_duplicate(): void
    {
        // Trait tenant already has a company; updating should keep one company.
        $payload = [
            'ruc' => '0990012345001',
            'business_name' => 'Nombre Actualizado',
            'address' => 'Nueva direccion',
            'email' => 'nuevo@example.com',
            'taxpayer_type' => 'natural',
            'sri_environment' => '2',
        ];

        $this->postJson('/api/v1/onboarding/company', $payload)
            ->assertOk()
            ->assertJsonPath('data.business_name', 'Nombre Actualizado');

        $this->assertSame(1, Company::where('tenant_id', $this->tenant->id)->count());
    }

    public function test_company_rejects_bad_ruc(): void
    {
        $second = $this->createSecondTenant();
        \Laravel\Sanctum\Sanctum::actingAs($second['user']);

        $this->postJson('/api/v1/onboarding/company', [
            'ruc' => '123', // too short / not 13 digits
            'business_name' => 'X',
            'address' => 'Y',
            'email' => 'x@example.com',
            'taxpayer_type' => 'natural',
            'sri_environment' => '1',
        ])->assertStatus(422)
            ->assertJsonValidationErrors(['ruc']);
    }

    public function test_establishment_creates_branch_and_emission_point_idempotently(): void
    {
        $second = $this->createSecondTenant();
        \Laravel\Sanctum\Sanctum::actingAs($second['user']);

        // Create company first.
        $this->postJson('/api/v1/onboarding/company', [
            'ruc' => '1790012345001',
            'business_name' => 'Empresa Demo',
            'address' => 'Direccion',
            'email' => 'demo@example.com',
            'taxpayer_type' => 'natural',
            'sri_environment' => '1',
        ])->assertCreated();

        $first = $this->postJson('/api/v1/onboarding/establishment', [
            'address' => 'Matriz address',
        ]);
        $first->assertOk()
            ->assertJsonPath('data.branch.code', '001')
            ->assertJsonPath('data.emission_point.code', '001');

        $branchId = $first->json('data.branch.id');
        $epId = $first->json('data.emission_point.id');

        // Re-submitting with same codes must update, not duplicate.
        $second2 = $this->postJson('/api/v1/onboarding/establishment', [
            'address' => 'Updated address',
        ]);
        $second2->assertOk()
            ->assertJsonPath('data.branch.id', $branchId)
            ->assertJsonPath('data.emission_point.id', $epId)
            ->assertJsonPath('data.branch.address', 'Updated address');

        $this->assertSame(1, \App\Models\Tenant\Branch::where('tenant_id', $second['tenant']->id)->count());
        $this->assertSame(1, EmissionPoint::where('tenant_id', $second['tenant']->id)->count());
    }

    public function test_establishment_imports_open_sri_establishments_when_requested(): void
    {
        \Illuminate\Support\Facades\Http::fake([
            '*Establecimiento*' => \Illuminate\Support\Facades\Http::response([
                [
                    'nombreFantasiaComercial' => null,
                    'direccionCompleta' => 'GUAYAS / GUAYAQUIL / XIMENA',
                    'estado' => 'ABIERTO',
                    'numeroEstablecimiento' => '002',
                    'matriz' => 'SI',
                ],
                [
                    'nombreFantasiaComercial' => 'SUCURSAL NORTE',
                    'direccionCompleta' => 'PICHINCHA / QUITO / NORTE',
                    'estado' => 'ABIERTO',
                    'numeroEstablecimiento' => '003',
                    'matriz' => 'NO',
                ],
                [
                    'nombreFantasiaComercial' => 'CERRADA',
                    'direccionCompleta' => 'LOS RIOS / VINCES',
                    'estado' => 'CERRADO',
                    'numeroEstablecimiento' => '001',
                    'matriz' => 'NO',
                ],
            ]),
        ]);

        $second = $this->createSecondTenant();
        \Laravel\Sanctum\Sanctum::actingAs($second['user']);

        $this->postJson('/api/v1/onboarding/company', [
            'ruc' => '1207481803001',
            'business_name' => 'Empresa Demo',
            'address' => 'Direccion',
            'email' => 'demo@example.com',
            'taxpayer_type' => 'natural',
            'sri_environment' => '1',
        ])->assertCreated();

        $response = $this->postJson('/api/v1/onboarding/establishment', [
            'code' => '002',
            'address' => 'GUAYAS / GUAYAQUIL / XIMENA',
            'import_sri_establishments' => true,
        ]);

        $response->assertOk()
            ->assertJsonPath('data.branch.code', '002')
            ->assertJsonPath('data.imported_branches.0.code', '003');

        // Matriz (002) + sucursal abierta importada (003); la cerrada (001) no
        $this->assertSame(2, \App\Models\Tenant\Branch::where('tenant_id', $second['tenant']->id)->count());
        $this->assertDatabaseHas('branches', [
            'tenant_id' => $second['tenant']->id,
            'code' => '003',
            'name' => 'SUCURSAL NORTE',
            'is_main' => false,
        ]);

        // La importada queda con punto de emisión operativo
        $imported = \App\Models\Tenant\Branch::where('tenant_id', $second['tenant']->id)
            ->where('code', '003')->first();
        $this->assertSame(1, $imported->emissionPoints()->count());
    }
}
