<?php

namespace Database\Seeders;

use App\Models\Billing\Plan;
use Illuminate\Database\Seeder;

class PlanSeeder extends Seeder
{
    public function run(): void
    {
        // Remove legacy Starter plan if it exists
        Plan::where('slug', 'starter')->delete();

        $plans = [
            [
                'name' => 'Emprendedor',
                'slug' => 'emprendedor',
                'description' => 'Para emprendedores y freelancers que necesitan facturar regularmente.',
                'price_monthly' => 4.99,
                'price_yearly' => 49.99,
                'max_documents_per_month' => 50,
                'max_users' => 3,
                'max_companies' => 1,
                'max_emission_points' => 2,
                'has_electronic_signature' => true,
                'has_api_access' => false,
                'has_inventory' => false,
                'has_pos' => false,
                'has_recurring_invoices' => false,
                'has_proformas' => true,
                'has_ats' => true,
                'has_thermal_printer' => false,
                'has_advanced_reports' => false,
                'has_whitelabel_ride' => false,
                'has_webhooks' => false,
                'has_client_portal' => false,
                'has_multi_currency' => false,
                'has_accountant_access' => true,
                'has_ai_categorization' => false,
                'support_level' => 'email',
                'support_response_hours' => 48,
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 1,
                'trial_days' => 0,
            ],
            [
                'name' => 'Negocio',
                'slug' => 'negocio',
                'description' => 'Ideal para PyMEs con operaciones frecuentes y necesidad de control de inventario.',
                'price_monthly' => 14.99,
                'price_yearly' => 149.99,
                'max_documents_per_month' => -1,
                'max_users' => 10,
                'max_companies' => 3,
                'max_emission_points' => 5,
                'has_electronic_signature' => true,
                'has_api_access' => true,
                'has_inventory' => true,
                'has_pos' => true,
                'has_recurring_invoices' => true,
                'has_proformas' => true,
                'has_ats' => true,
                'has_thermal_printer' => true,
                'has_advanced_reports' => true,
                'has_whitelabel_ride' => false,
                'has_webhooks' => true,
                'has_client_portal' => true,
                'has_multi_currency' => false,
                'has_accountant_access' => true,
                'has_ai_categorization' => false,
                'support_level' => 'email',
                'support_response_hours' => 24,
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 2,
                'trial_days' => 0,
            ],
            [
                'name' => 'Profesional',
                'slug' => 'profesional',
                'description' => 'Para empresas en crecimiento que necesitan funcionalidades avanzadas y múltiples sucursales.',
                'price_monthly' => 34.99,
                'price_yearly' => 349.99,
                'max_documents_per_month' => -1,
                'max_users' => -1,
                'max_companies' => -1,
                'max_emission_points' => -1,
                'has_electronic_signature' => true,
                'has_api_access' => true,
                'has_inventory' => true,
                'has_pos' => true,
                'has_recurring_invoices' => true,
                'has_proformas' => true,
                'has_ats' => true,
                'has_thermal_printer' => true,
                'has_advanced_reports' => true,
                'has_whitelabel_ride' => true,
                'has_webhooks' => true,
                'has_client_portal' => true,
                'has_multi_currency' => true,
                'has_accountant_access' => true,
                'has_ai_categorization' => true,
                'support_level' => 'priority',
                'support_response_hours' => 8,
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 3,
                'trial_days' => 0,
            ],
            [
                'name' => 'Enterprise',
                'slug' => 'enterprise',
                'description' => 'Solución personalizada para grandes empresas con necesidades específicas.',
                'price_monthly' => 99.00,
                'price_yearly' => 990.00,
                'max_documents_per_month' => -1,
                'max_users' => -1,
                'max_companies' => -1,
                'max_emission_points' => -1,
                'has_electronic_signature' => true,
                'has_api_access' => true,
                'has_inventory' => true,
                'has_pos' => true,
                'has_recurring_invoices' => true,
                'has_proformas' => true,
                'has_ats' => true,
                'has_thermal_printer' => true,
                'has_advanced_reports' => true,
                'has_whitelabel_ride' => true,
                'has_webhooks' => true,
                'has_client_portal' => true,
                'has_multi_currency' => true,
                'has_accountant_access' => true,
                'has_ai_categorization' => true,
                'support_level' => 'dedicated',
                'support_response_hours' => 1,
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 4,
                'trial_days' => 0,
            ],
        ];

        foreach ($plans as $plan) {
            Plan::updateOrCreate(['slug' => $plan['slug']], $plan);
        }
    }
}
